print("Какова окружность вашего колеса в миллиметрах?")
circle=int(input())
print('Сколько оборотов колеса произошло за время вашего путешествия?')
turnovers=int(input())
print('Сколько минут вы ездили на велосипеде?')
minutes=int(input())
distance=turnovers*(circle/10**6)
print(f"Вы проехали {distance}km")
average_speed=distance/(minutes/60)
print(f"Вы проехали со средней скоростью {round(average_speed,2)}kmh")
